version: '3'

x-spark-common: &spark-common
  image: bitnami/spark:latest
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
  networks:
    - project-work
  deploy:
    resources:
      limits:
        memory: 2g

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - airflow.env
  volumes:
    - ./jobs:/opt/airflow/jobs
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./data:/opt/airflow/data
    - ./notebook:/opt/airflow/notebook
    - ./config.ini:/opt/airflow/config.ini
    - ./airflow-service-acc.json:/opt/airflow/airflow-service-acc.json
  environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/airflow-service-acc.json
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  depends_on:
    - postgres
  networks:
    - project-work
  deploy:
    resources:
      limits:
        memory: 4g

services:
  spark-master:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"

  spark-worker:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077

  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    networks:
      - project-work

  webserver:
    <<: *airflow-common
    command: bash -c "airflow db upgrade && airflow webserver"
    ports:
      - "8080:8080"
    depends_on:
      - scheduler

  scheduler:
    <<: *airflow-common
    command: bash -c "airflow db upgrade && airflow users create --username admin --firstname admin --lastname admin --role Admin --email vinayak1ga19cs184@gmail.com --password admin && airflow scheduler"
    depends_on:
      - postgres

networks:
  project-work:
